# This workflow file runs the script every day at midnight.
name: Process Deprecated Apps
on:
# run on demand
  workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * *'
jobs:
    process_deprecated_apps:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
            uses: actions/checkout@v2
        - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
            node-version: '14'
        - name: Install gh
            run: |
            curl -sL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt-get update
            sudo apt-get install gh
        - name: Run script
            run: |
            bash .github/workflows/proc_deprecated.sh
     
# TODO
# Add a job to find merged PRs matching this pattern that have been closed for more than 7 days and delete the branch
# Add a job to find PRs that have been open for more than 17 days and close them

# Path: .github/workflows/proc_deprecated.sh
#!/bin/bash


     